### ISSUE TITLE
RAFT Deployment error

### ISSUE THREAD

**Issue by varunneelakantan** [microsoft/rest-api-fuzz-testing#169]
I am getting the below error when trying to deploy RAFT:

Creating Key Vault event subscription
args: az eventgrid event-subscription create --name OnSecretChanged --source-resource-id /subscriptions/XXXXX/resourceGroups/XX-raft/providers/Microsoft.KeyVault/vaults/XX-raft-1fcb-kv --endpoint /subscriptions/XXXXX/resourceGroups/XX-raft/providers/Microsoft.Web/sites/XX-raft-1fcb-orchestrator/functions/OnSecretChanged --endpoint-type azurefunction --included-event-types Microsoft.KeyVault.SecretNewVersionCreated

std error: ERROR: Deployment failed. Correlation ID: XXXXX. Destination azure endpoint not found. Resource details: resourceId: /subscriptions/XXXXX/resourceGroups/XX-raft/providers/Microsoft.Web/sites/XX-raft-1fcb-orchestrator/functions/OnSecretChanged. Resource should pre-exist before attempting this operation. Activity id:XXXX, timestamp: 3/25/2021 12:47:45 AM (UTC).

AZ Version: 2.20.0

**Comment by stishkin** [comment]
@varunneelakantan  - hi this is known issue. Just re-run deployment, and it should work.

@mgreisen - should you take a look at this one ?

**Comment by mgreisen** [comment]
The issue here is that the orchestrator needs to be running when the event subscription is made. During an initial deployment this can take a little longer because the image needs to be downloaded. Normally this means running the deployment a second time (which is safe) will fix this issue.

**Comment by mgreisen** [comment]
PR https://github.com/microsoft/rest-api-fuzz-testing/pull/171
