### ISSUE TITLE
Minimal example using raft_local.py

### ISSUE THREAD

**Issue by DavidFarago** [microsoft/rest-api-fuzz-testing#190]
Is it possible to use `raft_local.py` to fuzz-test purely locally, without cloud service? 

All `/cli/samples` have a run Python script that expects a `default.json` and aborts since I don't have it. I was able to create one with default empty strings for all attributes using `raft.py job create`, but the attributes seem to be for Azure configuration. So I guess I do not need `default.json` when using `raft_local.py`!? 

Is there a sample or description somewhere on how to use `raft_local.py`? Do I need `jobStatusWebhookUrl` and `bugFoundWebhookUrl` for `raft_local.py`, too?

-----------

In detail I tried the following using `raft_local.py`'s help output and some guesswork:
1) change `storage, secrets = init_local(work_dir)` to `storage, secrets, events_sink = init_local(work_dir)` in `raft_local.py`
2) `python raft_local.py local init`
3) Define a `job1.json` as in step 3 of https://github.com/microsoft/rest-api-fuzz-testing/blob/main/docs/how-to-submit-a-job.md, changing `apiSpecification` to a list of strings, thus making it valid json
4) `python raft_local.py job create --file job1.json`
5) The log shows:
`creating job ...`
pulling Zapp and Dredd from Docker
finally the traceback (most recent call last):
  File "raft_local.py", line 654, in <module>
    run(vars(args))
  File "raft_local.py", line 594, in run
    cli.new_job(job_config, args.get('jobStatusWebhookUrl'), args.get('bugFoundWebhookUrl'))
  File "raft_local.py", line 523, in new_job
    test_task_container_names = self.start_test_tasks(job_config, task_index, test_services_startup_delay, job_id, work_dir, job_dir, job_events, bridge_name)
  File "raft_local.py", line 392, in start_test_tasks
    tt['targetConfiguration'] = testTasks['targetConfiguration']
  File "/home/davef/git/rest-api-fuzz-testing/cli/raft_sdk/raft_common.py", line 52, in __getitem__
    return super(RaftJsonDict, self).__getitem__(key)
KeyError: 'targetConfiguration'
6) Since I am most interested in RESTler, I changed `job1.json` to `job2.json` containing only one task, with `toolName` being `RESTler`.
7) `python raft_local.py job create --file job2.json`
8) as 5)
9) `jobStatusWebhookUrl` and `bugFoundWebhookUrl` sound optional for `raft_local.py`, so (why) do I need them?
How do I get my task.config to contain `targetConfiguration` (see function `start_test_tasks`)? I cannot find `targetConfiguration` in `RaftJobConfig` or in https://github.com/microsoft/rest-api-fuzz-testing/blob/main/docs/how-to-submit-a-job.md.
Is it generated from `targetEndpointConfiguration`? My `job2.json` contains:
```
{
  "testTasks": {
    "targetEndpointConfiguration": {
      "apiSpecification": [
          "file:///home/davef/git/mediform/scheduling-server/openapi_tmp.json"
        ],
      "endpoint": "http://localhost:8088"
    },
    "tasks": [
      {
        "toolName": "RESTler",
        "outputFolder" : "restler-results-output-folder"
      }
    ]
  }
}
```
Is this related to point 3 above? Or is my `openapi_tmp.json` problematic? I created it from my `openapi.yaml` using a generic yaml2json transformation.

**Comment by stishkin** [comment]
@DavidFarago 

raft_local.py does not require a cloud service. The machine that runs it has to have docker installed and python.

We support same job configurations as the cloud service.

Thank you for pointing out documentation issues, we'll fix those. 

Our samples are up-to-date  though, since we do run those on regular basis.

https://github.com/microsoft/rest-api-fuzz-testing/blob/main/cli/samples/restler/single-task-compile-test-fuzz/run.json

The sample above can be condensed a bit, by keeping only one RESTler task as follows:

{
  "namePrefix": "sample-",
  "webhook": {
    "name": "sample"
  },
  
  "testTasks": {
    "targetConfiguration" : {
      "endpoint" : "https://petstore.swagger.io",
      "apiSpecifications": [
        "https://petstore.swagger.io/v2/swagger.json"
      ]
    },
    "tasks": [
      {
        "toolName": "RESTler",
        "outputFolder": "restler-petstorev2",
        "toolConfiguration": {
          "tasks": [
                {"task": "Compile"}, 
                
                {"task" : "Test"}, 
                
                {
                    "task" : "Fuzz",
                    "runConfiguration" : {
                      "Duration" : "00:10:00"
                    }
                }
            ]
        }
      }
    ]
  }
}

**Comment by DavidFarago** [comment]
Thanks, @stishkin. Unfortunately, I am still having problems:

I adapted your condensed job spec into: 
```
{
  "namePrefix": "sample-",
  "webhook": {
    "name": "sample"
  },  
  "testTasks": {
    "targetConfiguration" : {
	"endpoint": "http://localhost:8088",
      "apiSpecifications": [
        "file:///home/davef/git/mediform/scheduling-server/openapi_tmp.json"
      ]
    },
    "tasks": [
      {
        "toolName": "RESTler",
        "outputFolder": "restler-job3",
        "toolConfiguration":
          {
            "tasks": [
              {
                "task": "Compile"
	      }, 
              {
	        "task" : "Test"
	      }, 
              {
                "task" : "Fuzz",
	        "runConfiguration" :
		  {
                    "Duration" : "00:10:00"
                  }
              }
            ]
          }
      }
    ]
  }
}
```
But when I call `python raft_local.py job create --file job3.json` I get
```
{'namePrefix': 'sample-', 'webhook': {'name': 'sample'}, 'testTasks': {'targetConfiguration': {'endpoint': 'http://localhost:8088', 'apiSpecifications': ['file:///home/davef/git/mediform/scheduling-server/openapi_tmp.json']}, 'tasks': [{'toolName': 'RESTler', 'outputFolder': 'restler-job3', 'toolConfiguration': {'tasks': [{'task': 'Compile'}, {'task': 'Test'}, {'task': 'Fuzz', 'runConfiguration': {'Duration': '00:10:00'}}]}}]}}
creating job ea87f694-d7d6-49c1-8b2f-d4f0b8f8a8cd
v3.latest: Pulling from restapifuzztesting/restler-agent
Digest: sha256:b9ab8b4c1b9bbe9586ec7d66b43b9667b0b76e919cb4c2828c2d9c4f9a851914
Status: Image is up to date for mcr.microsoft.com/restapifuzztesting/restler-agent:v3.latest
mcr.microsoft.com/restapifuzztesting/restler-agent:v3.latest

Running docker with command : run -d -t --no-healthcheck --privileged --user="root" --entrypoint="" --workdir="/" --name RESTler-ea87f694-d7d6-49c1-8b2f-d4f0b8f8a8cd-0 --mount type=bind,source="/home/davef/git/rest-api-fuzz-testing/cli/local/storage/ea87f694-d7d6-49c1-8b2f-d4f0b8f8a8cd/restler-job3",target="/work_dir_ea87f694-d7d6-49c1-8b2f-d4f0b8f8a8cd" --mount type=bind,source="/home/davef/git/rest-api-fuzz-testing/cli/local/events_sink/ea87f694-d7d6-49c1-8b2f-d4f0b8f8a8cd/restler-job3",target="/raft-events-sink" --mount type=bind,source="/home/davef/git/rest-api-fuzz-testing/cli/raft-tools",target="/raft-tools",readonly   --env RAFT_JOB_ID="ea87f694-d7d6-49c1-8b2f-d4f0b8f8a8cd" --env RAFT_CONTAINER_GROUP_NAME="ea87f694-d7d6-49c1-8b2f-d4f0b8f8a8cd" --env RAFT_WORK_DIRECTORY="/work_dir_ea87f694-d7d6-49c1-8b2f-d4f0b8f8a8cd" --env RAFT_APP_INSIGHTS_KEY="00000000-0000-0000-0000-000000000000" --env RAFT_SITE_HASH="0" --env RAFT_SB_OUT_SAS="dummy_sas" --env RAFT_LOCAL="Developer" --env RESTLER_TELEMETRY_OPTOUT="0" --env RAFT_TASK_INDEX="0" --env RAFT_CONTAINER_NAME="ea87f694-d7d6-49c1-8b2f-d4f0b8f8a8cd_0" --env RAFT_STARTUP_DELAY="0" --env RAFT_RUN_CMD="/bin/sh /work_dir_ea87f694-d7d6-49c1-8b2f-d4f0b8f8a8cd/task-run.sh" --env RAFT_TOOL_RUN_DIRECTORY="/raft-tools/tools/RESTler" --env RAFT_POST_RUN_COMMAND="" --env RAFT_CONTAINER_SHELL="/bin/sh"  mcr.microsoft.com/restapifuzztesting/restler-agent:v3.latest /bin/sh /work_dir_ea87f694-d7d6-49c1-8b2f-d4f0b8f8a8cd/task-run.sh
bf61a3a426d567b78936ab8d5734e6fc75dde27ed6c585e51e1c17c05f4ab698

Waiting for containers: RESTler-ea87f694-d7d6-49c1-8b2f-d4f0b8f8a8cd-0
Agent: ea87f694-d7d6-49c1-8b2f-d4f0b8f8a8cd_0    Tool: RESTler    State: Created
======================
[{'Name': '/RESTler-ea87f694-d7d6-49c1-8b2f-d4f0b8f8a8cd-0', 'Status': 'exited', 'ExitCode': 2, 'ErrorMessage': ''}]
Job finished, cleaning up job containers
```
In `local/events_sink/ea87f694-d7d6-49c1-8b2f-d4f0b8f8a8cd/restler-job3/*.json` I find
```
{
  "EventType": "JobStatus",
  "Message": {
    "Tool": "RESTler",
    "JobId": "ea87f694-d7d6-49c1-8b2f-d4f0b8f8a8cd",
    "State": "Error",
    "UtcEventTime": "2021-04-28T12:14:04.3511893Z",
    "Details": {
      "Error": "Only 'http' and 'https' schemes are allowed. (Parameter 'value')"
    },
    "AgentName": "ea87f694-d7d6-49c1-8b2f-d4f0b8f8a8cd_0"
  }
}
```
Is this a problem with my "file:///home/davef/git/mediform/scheduling-server/openapi_tmp.json"? I created this json file out of my valid `openapi.yaml` we have in use.

**Comment by DavidFarago** [comment]
Sample `self-contained/swagger-petstore` has a readme.md telling me to execute `python run.py`, but that yields
```
Traceback (most recent call last):
  File "run.py", line 63, in <module>
    run(os.path.join(cur_dir, "restler.compile.json"),
  File "run.py", line 14, in run
    cli = RaftCLI()
  File "/home/davef/git/rest-api-fuzz-testing/cli/samples/restler/self-contained/swagger-petstore/../../../../raft_sdk/raft_service.py", line 117, in __init__
    with open(os.path.join(
FileNotFoundError: [Errno 2] No such file or directory: '/home/davef/git/rest-api-fuzz-testing/cli/raft_sdk/../defaults.json'
```
I do not find a defaults.json in your whole repo. Using the `defaults.json` I created as described in my first post, i.e.
```
{
    "subscription": "",
    "deploymentName": "",
    "region": "",
    "metricsOptIn": true,
    "useAppInsights": true,
    "registry": "mcr.microsoft.com"
}
```
I get 
```
Traceback (most recent call last):
  File "run.py", line 63, in <module>
    run(os.path.join(cur_dir, "restler.compile.json"),
  File "run.py", line 14, in run
    cli = RaftCLI()
  File "/home/davef/git/rest-api-fuzz-testing/cli/samples/restler/self-contained/swagger-petstore/../../../../raft_sdk/raft_service.py", line 123, in __init__
    self.definitions = RaftDefinitions(self.context)
  File "/home/davef/git/rest-api-fuzz-testing/cli/samples/restler/self-contained/swagger-petstore/../../../../raft_sdk/raft_common.py", line 229, in __init__
    self.sub_suffix = self.subscription.split('-')[1]
IndexError: list index out of range
```

**Comment by stishkin** [comment]
@DavidFarago 
python run.py is used for when you running RAFT in Azure. 

If you want to run local only <- then that script will not work.


Can you share scenario that you would like to run, and I can provide you with sample that will work with Raft-Local

**Comment by mgreisen** [comment]
@DavidFarago I've added a doc named how-to-use-raft-local.md that might help. The PR also fixed the small issue in the init command you pointed out in your list above.

**Comment by DavidFarago** [comment]
Thank you very much, your messages and `how-to-use-raft-local.md` helped. 

I now got `raft-local` running not only on petstore, and my yaml resp. json openapi file into the docker image.

However, using a yaml openapi specification yields
```
Agent: 00cd2457-f65c-4ad2-acaa-44cf916c65b9_0    Tool: RESTler    State: Error
Details:
Error : File /open-api-specs/openapi.yaml is not a valid JSON file due to Failed to validate /open-api-specs/openapi.yaml due to Unexpected character encountered while parsing value: o. Path '', line 0, position 0.. Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: o. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.FSharpLu.Json.Compact.deserializeFile[T](String file)
   at RESTlerAgent.validateJsonFile(String filePath) in /home/vsts/work/1/s/src/Agent/RESTlerAgent/AgentMain.fs:line 189
```
in spite of RESTler being able to handle yaml files (`restler-quick-start.py --api_spec_path ../scheduling-server/openapi.yaml --restler_drop_dir /RESTler --ip 127.0.0.1 --port 8088` does work).

**Comment by DavidFarago** [comment]
About potential issue 1. " It might be that you might need to get your x": x is "docker networking configured"? 

Can I somehow configure `raft-local` to use `docker run --network="host"`?

**Comment by stishkin** [comment]
right now we do have "host" as networking (see docker_create_bridge function in  raft_local)

We are working on moving to bridge networking, since that will simplify authentication scenarios, and also we can move lots of duplicate code into a dedicated "utility" container.

I will fix the "yaml" open API spec issue for next release. Should be coming out soon.

**Comment by stishkin** [comment]
@DavidFarago  -> I'll make it an optional command line parameter to keep "host" networking during run

**Comment by DavidFarago** [comment]
Thanks a lot. But I see in my API logs that restler does not reach my host's localhost. 

The `raft-local` output tail is
```
Agent: e6d0fa7e-bd08-46de-a96c-8ee1767aa3fb_0:1    Tool: RESTler    State: TaskCompleted
Details:
Experiment : experiment46
TaskType : Fuzz
finalSpecCoverage : 0 / 36
numberOfBugsFound : 0
======================
Agent: e6d0fa7e-bd08-46de-a96c-8ee1767aa3fb_0    Tool: RESTler    State: Completed
======================
d[{'Name': '/RESTler-e6d0fa7e-bd08-46de-a96c-8ee1767aa3fb-0', 'Status': 'exited', 'ExitCode': 0, 'ErrorMessage': ''}, {'Name': '/ZAP-e6d0fa7e-bd08-46de-a96c-8ee1767aa3fb-1', 'Status': 'exited', 'ExitCode': 0, 'ErrorMessage': ''}]
Job finished, cleaning up job containers
``` 
exit code 0 means no problems detected? When an endpoint is not at all reachable, does raft / restler /zap not detect a problem?

When I switch to 192.168.31.55:8088, I get the same `raft-local` output and no new messages in my API logs (while `restler-quick-start.py --api_spec_path ../scheduling-server/openapi.yaml --restler_drop_dir /RESTler --ip 192.168.31.55 --port 8088` does yield output and new messages in my API logs).

**Comment by stishkin** [comment]
Exit code 0 is whatever exit code returned by the tool. 
In this case RESTler and ZAP both exited with 0. 

There should be logs produced by RESTler run. And in the network log there should be details on why host is not reached.

My guess is that restler quick start sets "SSL" use to false by default. 

RAFT sets SSL use in RESTler to True by default. 
To disable SSL 
```json
"toolConfiguration": {
          "task": "Fuzz",
          "runConfiguration": {
            "useSsl" : false,                        <<<<< disable not use SSL
            "Duration" : "00:10:00"
          }
        }
```

Did ZAP produce a report in your case ?

**Comment by DavidFarago** [comment]
Actually, I found the following at the end of the zap logs:
```
226838 [ZAP-Import-OpenAPI-1] WARN  org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter - Failed to build/normalise the API URL using Server URL: /
java.lang.IllegalArgumentException: The scheme must not be null.
	at org.zaproxy.zap.extension.openapi.converter.swagger.UriBuilder.validateNotNull(UriBuilder.java:279) ~[openapi-beta-18.zap:?]
	at org.zaproxy.zap.extension.openapi.converter.swagger.UriBuilder.build(UriBuilder.java:252) ~[openapi-beta-18.zap:?]
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.createApiUrls(SwaggerConverter.java:258) [openapi-beta-18.zap:?]
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:181) [openapi-beta-18.zap:?]
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:158) [openapi-beta-18.zap:?]
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$3.run(ExtensionOpenApi.java:277) [openapi-beta-18.zap:?]
226845 [ZAP-Import-OpenAPI-1] WARN  org.zaproxy.zap.extension.openapi.ExtensionOpenApi - Unable to obtain any server URL from the definition.
org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerException: Unable to obtain any server URL from the definition.
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.createApiUrls(SwaggerConverter.java:271) ~[openapi-beta-18.zap:?]
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:181) ~[openapi-beta-18.zap:?]
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:158) ~[openapi-beta-18.zap:?]
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$3.run(ExtensionOpenApi.java:277) [openapi-beta-18.zap:?]
```
Does ` Unable to obtain any server URL from the definition` mean Zap wants to obtain the server URL from the openapi definition? I believe an openapi specification does not require a server object. Or is there some other definition for Zap where the server was not set correctly? Then maybe this is a configuration problem on my part?

Similarly, in the RESTler logs, I find a lot of log messages like `2021-04-29 19:20:45.555: 'Exception Creating Socket: check_hostname requires server_hostname'`. 

So `"endpoint": "http://192.168.31.55:8088"` is not sufficient in the `job.json`?

**Comment by stishkin** [comment]
You have correct endpoint setting.

Could you share that snipped of your job.json ? or if possible all of the job.json ? so I could verify that the file has correct schema ?

**Comment by DavidFarago** [comment]
Good guess with SSL :+1: 

My API logs are showing that requests are being served now, and RESTler found 2 bugs already.

The `job.json` that works for me is:
```json
{
  "ReadOnlyFileShareMounts": [
    {
      "fileShareName": "/home/davef/git/rest-api-fuzz-testing/cli/local/storage/my-specs",
       "mountPath": "/open-api-specs"
    }
  ],
  "testTasks": {
    "targetConfiguration": {
	"apiSpecifications": [ "/open-api-specs/openapi.json" ],
	"endpoint": "http://192.168.31.55:8088"
    },
    "tasks": [
	{
	  "toolName": "RESTler",
	  "outputFolder": "restler-logs",
	  "toolConfiguration": {
	    "tasks": [
	      {
		"task": "compile"
	      },
	      {
		"task": "Fuzz",
		"runConfiguration": {
                  "Duration": "00:30:00",
                  "useSsl": false
		}
	      }
	    ]
	  }
	},
	{
	  "toolName": "ZAP",
	  "outputFolder": "zap-logs"
	}
    ]
  }
}
```

**Comment by stishkin** [comment]
You job configuration looks correct. 

Is your issue resolved or there are still problems ? 
Or does your RESTler task works correctly, but ZAP does not ?

**Comment by DavidFarago** [comment]
Exactly: my RESTler task works correctly, but ZAP does not.

But thanks a lot for getting the RESTler task up and running.
