### ISSUE TITLE
Allow localhost to test local api running on your host

### ISSUE THREAD

**Issue by DavidFarago** [microsoft/rest-api-fuzz-testing#193]
Remove 
```
        if len(test_target_container_names) == 0:
            # no bridge needed, since there are not "services under test" deployed
            # and therefore we are testing something deployed externally
            bridge_name = None
```
from `raft_local.py` because your system under test might be running directly on your host, not inside a docker image (own or RAFT). Setting `bridge_name` from `'host'` to `None` disables `localhost` for docker.

**Comment by stishkin** [comment]
Thank you, I will add your fix and we should have new release very soon

**Comment by stishkin** [comment]
Setting network to "host" works. Going to use "host" instead of None
