### ISSUE TITLE
Schemathesis Unhandled authentication configuration {'TxtToken'}

### ISSUE THREAD

**Issue by Sticcia** [microsoft/rest-api-fuzz-testing#198]
Running Schemathesis in a local deployment with the following configuration:
``` JSON
{
  "testTasks" : {
    "targetConfiguration": {
      "apiSpecifications": [
        "<specification-url>"
      ],
      "endpoint": "<endpoint-url>"
    },
    "tasks": [
      {
        "toolName": "Schemathesis",
        "outputFolder": "schemathesis",
        "keyVaultSecrets": [ "<token>" ],
        "authenticationMethod": {
            "TxtToken": "<token>"
        }
      }
    ]
  }
}
```
Where `<token>` is file in \cli\local\secrets\ containing:
`Basic <base64-auth-token>=`
Authentication token is handled correctly in run.py for Dredd and ZAP but not for Schemathesis.
Results in following if-statement skipped:
``` Python
if token:
  args.extend(["-H", f"Authorization: {token}"])
```
Hard-coding the same token seems to work:
In \cli\raft-tools\tools\Schemathesis\run.py, after line 41:
``` Python
args.extend(["-H", f"Authorization: Basic <base64-auth-token>="])
```

P.S.:
Consider adding an argument to disable TLS verification, I'm currently using the following:
``` Python
args.extend(["--request-tls-verify", "false"])
```

**Comment by stishkin** [comment]
Closing this one since there is #203  and I also opened #204 to address suggestion for turning off certificate validation
