### ISSUE TITLE
Using Examples in RESTler

### ISSUE THREAD

**Issue by LYDE1234** [microsoft/rest-api-fuzz-testing#202]
When I use the CompilerConfig members (UseBodyExamples, UseQueryExamples, DiscoverExamples, ExamplesDirectory), they all produce a "Could not find <member> on object of type 'CompileConfiguration'" in the RESTler agent. Other members, like "CustomDictionary" work fine so is this because the Examples parameters have not been implemented in Agent yet? Is there a way to work around this limitation.

**Comment by stishkin** [comment]
@LYDE1234

We have all Examples settings turn on by default (but they are not exposed as part of configuration). I can expose those settings to be configurable.

```
        UseQueryExamples = true
    
        UseBodyExamples = true
    
        /// When set to 'true', discovers examples and outputs them to a directory next to the grammar.
        /// If an existing directory exists, does not over-write it.
        DiscoverExamples = true
    
        /// The directory where the compiler should look for examples.
        /// If 'discoverExamples' is true, this directory will contain the
        /// example files that have been discovered.
        /// If 'discoverExamples' is false, every time an example is used in the
        /// Swagger file, RESTler will first look for it in this directory.
        ExamplesDirectory = workDirectory ++ "Examples"
    ```

**Comment by LYDE1234** [comment]
Thanks. It would be nice to have the properties be configurable, but the important part is that they're enabled by default.

**Comment by stishkin** [comment]
@LYDE1234

I'm going to release v4.0.1 
It has all example related RESTler options exposed
```
{
        "toolName": "RESTler",
        "outputFolder": "compile",
        "toolConfiguration": {
          "task": "Compile",
          "compileConfiguration" : {
            "discoverExamples" : false
          }
        }
}
```

**Comment by stishkin** [comment]
@LYDE1234  release is done, if you are on v4 you do not need to take any action and new changes should be available to you regardless if you are running in Azure or locally

**Comment by stishkin** [comment]
Also I found this RESTler document page helpful, since it has some missing information about

ExampleConfigFilePath 

https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/CompilerConfig.md

**Comment by LYDE1234** [comment]
Brilliant. Thanks.
