### ISSUE TITLE
RESTler token settings

### ISSUE THREAD

**Issue by Sticcia** [microsoft/rest-api-fuzz-testing#212]
I'm running a RESTler configuration in a local deployment with the following configuration.
```JSON
{
  "testTasks" : {
    "targetConfiguration": {
      "apiSpecifications": [
        "<specification-url>"
      ],
      "endpoint": "<endpoint-url>"
    },
    "tasks": [
      {
        "toolName": "RESTler",
        "outputFolder": "restler",
        "keyVaultSecrets": [ "TOKEN" ],
        "authenticationMethod": {
          "Token": "Token"
        },
        "toolConfiguration": {
          "tasks": [
            {
              "task": "Compile",
              "compileConfiguration": {
                "useRefreshableToken": true,
                "discoverExamples": true,
                "useBodyExamples": true,
                "useQueryExamples": true,
                "examplesDirectory": "Examples",
                "customDictionary": {
                  "customPayload": {
                    "id": [
                      "<some-ids>"
                    ]
                  }
                }
              }
            },
            {
              "task": "Test",
              "runConfiguration": {
                "Duration": "01:00:00",
                "useSsl": false
              }
            },
            {
              "task": "TestFuzzLean",
              "runConfiguration": {
                "Duration": "01:00:00",
                "useSsl": false
              }
            },
            {
              "task": "Fuzz",
              "runConfiguration": {
                "Duration": "01:00:00",
                "useSsl": false
              }
            }
          ]
        }
      }
    ]
  }
}
```

We are investigating the result which contains a few very similar bug buckets, like the following:
```
-> GET /ManagementServer/rest/cameras/2f207a49-077b-4ee4-93de-e8693afcef16/clientSettings/9504767D-20F5-4AEC-8DBE-0D6824B795CF HTTP/1.1\r\nAccept: application/json\r\nHost: dkta-0613sk0004.ta.rd.local\r\nAUTHORIZATION TOKEN\r\n\r\n
! producer_timing_delay 0
! max_async_wait_time 60
PREVIOUS RESPONSE: 'Exception: timed out'
```

It would be nice to read the `AUTHORIZATION TOKEN` (for debugging purposes).
I looked through the configurations and found some interesting values is `settings.json`:

![Screenshot_62](https://user-images.githubusercontent.com/5552940/122757999-90bb7b80-d298-11eb-9f24-a6917a8e07a8.png)

Can I set `"no_tokens_in_logs": false` I'd like to debug my current authentication issues and make sure the token is correctly passed to RESTler?
From my understanding the token is retrieved by the Python code in `"token_refresh_cmd"`. Is it possible to edit this somehow and pass the token manually?

**Comment by stishkin** [comment]
Hi, @Sticcia

Are you running Azure deployment of RAFT or local ? 

Right now we don't have a flag to show tokens in logs, but we can expose in next release (should be done very soon, since there is an update to RESTler coming out)

I see in your config SSL is set to false, but your target port is 443 is that intended ? 


As a current debugging option - you can add "isIdling" flag, that way the RESTler container will start but not going to run.
```
      "tasks": [
        {
          "toolName" : "RESTler",
          "isIdling" : true,
```

Then connect to RESTler container, and from there run
`wget http://localhost:8085/auth/Token/Token`
