### ISSUE TITLE
Support of certificate based authentication in RAFT for Restler

### ISSUE THREAD

**Issue by prat-bphc52** [microsoft/rest-api-fuzz-testing#233]
Restler provides a configuration in settings file where the path to certificate can be provided as "client_certificate_path". This works perfectly fine when using the RESTler tool locally. However there is no such option available in RAFT job definition to allow usage of client certificates for authenticating against the server.

Is it possible to enable this feature on RAFT?

**Comment by stishkin** [comment]
This change will be available in next release.

See [Certificate](https://github.com/microsoft/rest-api-fuzz-testing/blob/main/docs/authentication.md) authentication section.

**Comment by prat-bphc52** [comment]
Thank you so much @stishkin!
